---
- name: add file and write inside a file
  hosts: localhost
  tasks:
    - name: add file
      file:
        path: /tmp/new.txt
        state: touch
    - name: add lines inside a file
      blockinfile:
        path: /tmp/new.txt
        block: |
          hello
          hello1
    - name: install apache
      yum:
        name: httpd
    - name: start and enable apche
      systemd:
        name: httpd
        state: started
        enabled: true
